version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "npm "npm installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "testing stuff"
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - run: echo "hellooooooooooo!"
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
